backend:
  name: github
  repo: DeanoDee/zm-cloudsuite-content #replace with your username/repo

media_folder: static/assets

collections:
  - name: "home"
    label: "Home"
    folder: "_pages/home"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string"}
      - { name: "headline", label: "Headline", widget: "string" }
